spring:
  application:
    name: success-consumer
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

info:
  app:
    name: success-consumer
    description: Spring boot application with eureka client implementation
    version: 0.0.1-SNAPSHOT

kafka:
  servers: ${KAFKA_BOOTSTRAP_SERVER_LIST:http://localhost:9092}
  groupId: ${KAFKA_CONSUMER_GROUP_ID:1}
