
spring:
  application:
    name: router
server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

info:
  app:
    name: spring-cloud-eureka-client
    description: Kafka stream processor
    version: 0.0.1-SNAPSHOT

kafka:
  servers: ${KAFKA_BOOTSTRAP_SERVER_LIST:http://localhost:2181}